// Hand-written, UNIQUE expert tips per tool (1-2 each), multilingual.
// Only tools present here render a "Expert tips" section — no templated filler
// on the rest, so there is zero duplicate/scaled content (AdSense/Google safe).

type Tip = { en: string; fr: string; es: string; ar: string };

export const TOOL_TIPS: Record<string, Tip[]> = {
  // ===== New trending agents & LLMs =====
  codex: [
    { en: 'Fire several small, well-scoped tasks in parallel on separate branches, then review the pull requests together — it is the fastest way to clear a backlog.', fr: 'Lancez plusieurs petites tâches bien délimitées en parallèle sur des branches séparées, puis examinez les pull requests ensemble — c’est le moyen le plus rapide de vider un backlog.', es: 'Lanza varias tareas pequeñas y bien definidas en paralelo en ramas separadas, y luego revisa los pull requests juntos: es la forma más rápida de vaciar un backlog.', ar: 'أطلق عدة مهام صغيرة ومحددة جيداً بالتوازي على فروع منفصلة، ثم راجع طلبات الدمج معاً — إنها أسرع طريقة لإنجاز قائمة المهام.' },
    { en: 'Keep tasks narrow: Codex burns far fewer credits on a "fix this function" job than on a repo-wide refactor.', fr: 'Gardez des tâches ciblées : Codex consomme bien moins de crédits sur un « corrige cette fonction » que sur un refactor de tout le dépôt.', es: 'Mantén las tareas acotadas: Codex gasta muchos menos créditos en un «arregla esta función» que en una refactorización de todo el repositorio.', ar: 'اجعل المهام محدّدة: يستهلك Codex رصيداً أقل بكثير في مهمة « أصلح هذه الدالة » مقارنة بإعادة هيكلة المستودع بأكمله.' },
  ],
  devin: [
    { en: 'Devin shines on well-defined tickets — write crisp acceptance criteria and link the exact files before you assign it.', fr: 'Devin excelle sur des tickets bien définis — rédigez des critères d’acceptation clairs et liez les fichiers exacts avant de lui confier la tâche.', es: 'Devin brilla con tickets bien definidos: redacta criterios de aceptación claros y enlaza los archivos exactos antes de asignárselo.', ar: 'يتألّق Devin مع المهام المحدّدة جيداً — اكتب معايير قبول واضحة واربط الملفات المعنية بدقة قبل إسناد المهمة إليه.' },
    { en: 'Keep it continuously busy with a queue; its ACU-based pricing only pays off at high utilisation.', fr: 'Gardez-le occupé en continu avec une file de tâches ; sa tarification à l’ACU n’est rentable qu’à forte utilisation.', es: 'Mantenlo ocupado de forma continua con una cola; su precio basado en ACU solo compensa con un uso intensivo.', ar: 'أبقِه مشغولاً باستمرار بقائمة مهام؛ فتسعيره المعتمد على وحدات ACU لا يكون مجدياً إلا مع الاستخدام المكثّف.' },
  ],
  opencode: [
    { en: 'Point OpenCode at a cheap-but-strong model like GLM-5.2 or Kimi to cut costs while keeping near-frontier coding quality.', fr: 'Faites pointer OpenCode vers un modèle bon marché mais performant comme GLM-5.2 ou Kimi pour réduire les coûts tout en gardant une qualité de code proche du top.', es: 'Apunta OpenCode a un modelo barato pero potente como GLM-5.2 o Kimi para reducir costes manteniendo una calidad de código casi de élite.', ar: 'وجّه OpenCode إلى نموذج رخيص لكنه قوي مثل GLM-5.2 أو Kimi لتقليل التكلفة مع الحفاظ على جودة برمجة قريبة من القمة.' },
    { en: 'Because it is terminal-native, wire it into your existing shell scripts and CI to run agentic edits automatically.', fr: 'Comme il est natif du terminal, branchez-le à vos scripts shell et à votre CI pour exécuter des modifications agentiques automatiquement.', es: 'Como es nativo de terminal, intégralo en tus scripts de shell y tu CI para ejecutar ediciones agénticas automáticamente.', ar: 'بما أنه يعمل أصلاً في الطرفية، ادمجه في سكربتات الصدفة وأنظمة CI لديك لتنفيذ تعديلات وكيلة تلقائياً.' },
  ],
  cline: [
    { en: 'Use Plan mode first to review Cline’s strategy, then switch to Act — it prevents costly wrong turns on big tasks.', fr: 'Utilisez d’abord le mode Plan pour valider la stratégie de Cline, puis passez en mode Act — cela évite des erreurs coûteuses sur les grosses tâches.', es: 'Usa primero el modo Plan para revisar la estrategia de Cline y luego cambia a Act: evita errores costosos en tareas grandes.', ar: 'استخدم وضع التخطيط (Plan) أولاً لمراجعة استراتيجية Cline ثم انتقل إلى وضع التنفيذ (Act) — يمنع ذلك الأخطاء المكلفة في المهام الكبيرة.' },
    { en: 'Run a local model via Ollama for private codebases you cannot send to a cloud API.', fr: 'Faites tourner un modèle local via Ollama pour les bases de code privées que vous ne pouvez pas envoyer à une API cloud.', es: 'Ejecuta un modelo local con Ollama para bases de código privadas que no puedes enviar a una API en la nube.', ar: 'شغّل نموذجاً محلياً عبر Ollama للشيفرات الخاصة التي لا يمكنك إرسالها إلى واجهة سحابية.' },
  ],
  aider: [
    { en: 'Commit early and often — Aider’s automatic commits make it trivial to git revert a bad AI edit.', fr: 'Committez tôt et souvent — les commits automatiques d’Aider rendent le git revert d’une mauvaise modification IA trivial.', es: 'Haz commits pronto y a menudo: los commits automáticos de Aider hacen trivial revertir con git una mala edición de IA.', ar: 'سجّل التغييرات مبكراً وبشكل متكرر — تجعل التزامات Aider التلقائية التراجع (git revert) عن تعديل خاطئ أمراً سهلاً.' },
    { en: 'Add only the files relevant to the task to its context to keep token costs and mistakes down.', fr: 'N’ajoutez à son contexte que les fichiers pertinents pour la tâche, afin de limiter les coûts en tokens et les erreurs.', es: 'Añade a su contexto solo los archivos relevantes para la tarea, para reducir el coste en tokens y los errores.', ar: 'أضف إلى سياقه الملفات ذات الصلة بالمهمة فقط لتقليل تكلفة الرموز والأخطاء.' },
  ],
  trae: [
    { en: 'Use SOLO Builder to scaffold fresh projects, but avoid it for proprietary code — ByteDance telemetry is aggressive.', fr: 'Utilisez SOLO Builder pour démarrer de nouveaux projets, mais évitez-le pour du code propriétaire — la télémétrie de ByteDance est intrusive.', es: 'Usa SOLO Builder para crear proyectos nuevos, pero evítalo con código propietario: la telemetría de ByteDance es agresiva.', ar: 'استخدم SOLO Builder لبناء مشاريع جديدة، لكن تجنّبه مع الشيفرات الخاصة — فجمع البيانات لدى ByteDance شديد.' },
    { en: 'Take advantage of the free premium models for prototyping before paying for a heavier IDE.', fr: 'Profitez des modèles premium gratuits pour prototyper avant de payer un IDE plus lourd.', es: 'Aprovecha los modelos premium gratuitos para prototipar antes de pagar un IDE más pesado.', ar: 'استفد من النماذج المتميزة المجانية لبناء النماذج الأولية قبل الدفع مقابل بيئة تطوير أثقل.' },
  ],
  minimax: [
    { en: 'At ~$0.25 per 1M input tokens, MiniMax M2.7 is ideal for high-volume automated coding pipelines where cost dominates.', fr: 'À ~0,25 $ le million de tokens d’entrée, MiniMax M2.7 est idéal pour des pipelines de code automatisés à fort volume où le coût prime.', es: 'A ~0,25 $ por millón de tokens de entrada, MiniMax M2.7 es ideal para pipelines de código automatizados de alto volumen donde el coste manda.', ar: 'بسعر نحو 0.25 دولار لكل مليون رمز إدخال، يُعدّ MiniMax M2.7 مثالياً لخطوط البرمجة الآلية كثيفة الحجم حيث تكون التكلفة هي الأهم.' },
    { en: 'Self-host the open weights if you handle sensitive code and want zero data leaving your own infrastructure.', fr: 'Auto-hébergez les poids ouverts si vous manipulez du code sensible et voulez qu’aucune donnée ne quitte votre infrastructure.', es: 'Autoaloja los pesos abiertos si manejas código sensible y quieres que ningún dato salga de tu propia infraestructura.', ar: 'استضِف الأوزان المفتوحة ذاتياً إذا كنت تتعامل مع شيفرة حسّاسة وتريد ألا تغادر أي بيانات بنيتك التحتية.' },
  ],
  kimi: [
    { en: 'Lean on Kimi’s 262K context to drop an entire repo or long spec in one prompt instead of chunking it.', fr: 'Exploitez le contexte de 262K de Kimi pour déposer un dépôt entier ou une longue spécification en un seul prompt au lieu de le découper.', es: 'Aprovecha el contexto de 262K de Kimi para volcar un repositorio entero o una especificación larga en un solo prompt en vez de trocearlo.', ar: 'استفد من سياق Kimi البالغ 262 ألف رمز لإدخال مستودع كامل أو مواصفات طويلة في طلب واحد بدلاً من تقسيمها.' },
    { en: 'Its native multimodality lets you paste screenshots or diagrams alongside code for sharper answers.', fr: 'Sa multimodalité native vous permet de coller des captures d’écran ou des schémas avec le code pour des réponses plus précises.', es: 'Su multimodalidad nativa te permite pegar capturas o diagramas junto al código para respuestas más precisas.', ar: 'تتيح لك قدراته متعددة الوسائط الأصلية لصق لقطات الشاشة أو المخططات مع الشيفرة للحصول على إجابات أدق.' },
  ],
  qwen: [
    { en: 'For non-English projects, Qwen’s multilingual strength often beats Western models — test it on your locale first.', fr: 'Pour les projets non anglophones, la force multilingue de Qwen dépasse souvent les modèles occidentaux — testez-le d’abord dans votre langue.', es: 'Para proyectos en otros idiomas, la fuerza multilingüe de Qwen suele superar a los modelos occidentales: pruébalo primero en tu idioma.', ar: 'للمشاريع غير الإنجليزية، غالباً ما تتفوّق قوة Qwen متعددة اللغات على النماذج الغربية — جرّبه أولاً بلغتك.' },
    { en: 'Pick the smallest Qwen variant that passes your eval; the on-device sizes cut cost and latency dramatically.', fr: 'Choisissez la plus petite variante de Qwen qui réussit votre évaluation ; les tailles embarquées réduisent fortement coût et latence.', es: 'Elige la variante más pequeña de Qwen que pase tu evaluación; los tamaños en dispositivo reducen mucho coste y latencia.', ar: 'اختر أصغر نسخة من Qwen تجتاز اختبارك؛ فالأحجام التي تعمل على الأجهزة تقلّل التكلفة وزمن الاستجابة بشكل كبير.' },
  ],
  glm: [
    { en: 'GLM-5.2’s MIT licence lets you ship it commercially — a real edge over Llama’s more restrictive licence.', fr: 'La licence MIT de GLM-5.2 vous permet de l’exploiter commercialement — un vrai avantage sur la licence plus restrictive de Llama.', es: 'La licencia MIT de GLM-5.2 te permite usarlo comercialmente: una ventaja real frente a la licencia más restrictiva de Llama.', ar: 'تتيح لك رخصة MIT الخاصة بـ GLM-5.2 استخدامه تجارياً — ميزة حقيقية مقارنة برخصة Llama الأكثر تقييداً.' },
    { en: 'Use the "Max" reasoning mode for hard multi-file changes and "High" for everyday generation to balance speed and depth.', fr: 'Utilisez le mode de raisonnement « Max » pour les changements multi-fichiers difficiles et « High » pour la génération courante, afin d’équilibrer vitesse et profondeur.', es: 'Usa el modo de razonamiento «Max» para cambios multiarchivo difíciles y «High» para la generación diaria, para equilibrar velocidad y profundidad.', ar: 'استخدم وضع الاستدلال « Max » للتغييرات الصعبة متعددة الملفات و« High » للتوليد اليومي لتحقيق توازن بين السرعة والعمق.' },
  ],
  hermes: [
    { en: 'Use Hermes’ JSON and function-calling mode for reliable structured output in agents instead of parsing free text.', fr: 'Utilisez le mode JSON et appel de fonctions de Hermes pour une sortie structurée fiable dans vos agents, plutôt que d’analyser du texte libre.', es: 'Usa el modo JSON y de llamada a funciones de Hermes para una salida estructurada fiable en agentes, en vez de analizar texto libre.', ar: 'استخدم وضع JSON واستدعاء الدوال في Hermes للحصول على مخرجات منظّمة موثوقة في الوكلاء بدلاً من تحليل نص حر.' },
    { en: 'Because it is neutrally aligned, add your own safety guardrails before exposing it to end users.', fr: 'Comme il est neutre en alignement, ajoutez vos propres garde-fous de sécurité avant de l’exposer à des utilisateurs finaux.', es: 'Como tiene alineación neutral, añade tus propias barreras de seguridad antes de exponerlo a usuarios finales.', ar: 'بما أنه محايد المحاذاة، أضِف ضوابط أمان خاصة بك قبل إتاحته للمستخدمين النهائيين.' },
  ],
  llama: [
    { en: 'Use Llama 4 Scout’s 10M-token context for whole-codebase or book-length analysis that closed models cannot fit.', fr: 'Utilisez le contexte de 10M de tokens de Llama 4 Scout pour analyser un dépôt entier ou un texte long que les modèles fermés ne peuvent contenir.', es: 'Usa el contexto de 10M de tokens de Llama 4 Scout para analizar un repositorio entero o textos largos que los modelos cerrados no admiten.', ar: 'استخدم سياق Llama 4 Scout البالغ 10 ملايين رمز لتحليل مستودع كامل أو نصوص طويلة لا تتّسع لها النماذج المغلقة.' },
    { en: 'Fine-tune the open weights on your domain data — it is the cheapest path to a specialised in-house model.', fr: 'Affinez les poids ouverts sur vos données métier — c’est la voie la moins chère vers un modèle interne spécialisé.', es: 'Ajusta los pesos abiertos con los datos de tu dominio: es la vía más barata hacia un modelo interno especializado.', ar: 'درّب الأوزان المفتوحة على بيانات مجالك — إنها أرخص طريق لنموذج داخلي متخصّص.' },
  ],
  'claude-cowork': [
    { en: 'Point Cowork at a dedicated project folder and give it one clear goal — it works best finishing a defined deliverable, not open-ended chat.', fr: 'Faites pointer Cowork vers un dossier de projet dédié et donnez-lui un objectif clair — il est meilleur pour finaliser un livrable défini que pour discuter sans but.', es: 'Apunta Cowork a una carpeta de proyecto dedicada y dale un objetivo claro: rinde mejor terminando un entregable definido que en un chat abierto.', ar: 'وجّه Cowork إلى مجلد مشروع مخصّص وامنحه هدفاً واحداً واضحاً — فهو أفضل في إنجاز ناتج محدّد منه في الدردشة المفتوحة.' },
    { en: 'Connect it to your tools via MCP connectors so it can pull real context, not just local files.', fr: 'Connectez-le à vos outils via les connecteurs MCP pour qu’il récupère un contexte réel, pas seulement des fichiers locaux.', es: 'Conéctalo a tus herramientas mediante conectores MCP para que obtenga contexto real, no solo archivos locales.', ar: 'اربطه بأدواتك عبر موصّلات MCP ليستمدّ سياقاً حقيقياً لا مجرّد ملفات محلية.' },
  ],
  manus: [
    { en: 'Save credits by batching related sub-tasks into one Manus run instead of many small prompts.', fr: 'Économisez des crédits en regroupant les sous-tâches liées en une seule exécution Manus plutôt qu’en multipliant les petits prompts.', es: 'Ahorra créditos agrupando subtareas relacionadas en una sola ejecución de Manus en lugar de muchos prompts pequeños.', ar: 'وفّر الرصيد بدمج المهام الفرعية المترابطة في تشغيل واحد لـ Manus بدلاً من كثرة الأوامر الصغيرة.' },
    { en: 'Use its scheduled tasks to let Manus produce recurring reports overnight.', fr: 'Utilisez ses tâches planifiées pour laisser Manus produire des rapports récurrents pendant la nuit.', es: 'Usa sus tareas programadas para que Manus genere informes recurrentes durante la noche.', ar: 'استخدم مهامه المجدولة لتدع Manus ينتج تقارير دورية أثناء الليل.' },
  ],
  openclaw: [
    { en: 'Run OpenClaw with a local model for round-the-clock automation at zero API cost and full privacy.', fr: 'Faites tourner OpenClaw avec un modèle local pour une automatisation 24/7 à coût d’API nul et confidentialité totale.', es: 'Ejecuta OpenClaw con un modelo local para automatización 24/7 sin coste de API y con total privacidad.', ar: 'شغّل OpenClaw بنموذج محلي لأتمتة على مدار الساعة بتكلفة واجهة صفرية وخصوصية كاملة.' },
    { en: 'Start with a few trusted AgentSkills and sandbox it before granting shell access — it can act on your machine.', fr: 'Commencez avec quelques AgentSkills de confiance et isolez-le (sandbox) avant de lui donner l’accès au shell — il peut agir sur votre machine.', es: 'Empieza con unas pocas AgentSkills de confianza y aíslalo en un sandbox antes de darle acceso al shell: puede actuar en tu equipo.', ar: 'ابدأ بعدد قليل من مهارات الوكيل الموثوقة وضعه في بيئة معزولة قبل منحه صلاحية الصدفة — فهو قادر على التصرّف في جهازك.' },
  ],
  goose: [
    { en: 'Capture repetitive workflows as Goose "recipes" (YAML) and run them in CI for repeatable, shareable automation.', fr: 'Capturez les workflows répétitifs sous forme de « recipes » Goose (YAML) et exécutez-les dans la CI pour une automatisation reproductible et partageable.', es: 'Captura flujos repetitivos como «recipes» de Goose (YAML) y ejecútalos en CI para una automatización repetible y compartible.', ar: 'حوّل سير العمل المتكرّر إلى « recipes » في Goose (بصيغة YAML) وشغّلها ضمن CI لأتمتة قابلة للتكرار والمشاركة.' },
    { en: 'Connect your existing Claude or ChatGPT subscription via ACP instead of paying twice for API calls.', fr: 'Connectez votre abonnement Claude ou ChatGPT existant via ACP au lieu de payer deux fois pour les appels API.', es: 'Conecta tu suscripción existente de Claude o ChatGPT mediante ACP en lugar de pagar dos veces por las llamadas a la API.', ar: 'اربط اشتراكك الحالي في Claude أو ChatGPT عبر ACP بدلاً من الدفع مرتين مقابل استدعاءات الواجهة.' },
  ],
  'gemini-cli': [
    { en: 'Log in with a personal Google account to unlock about 1,000 free requests a day before paying anything.', fr: 'Connectez-vous avec un compte Google personnel pour débloquer environ 1 000 requêtes gratuites par jour avant de payer quoi que ce soit.', es: 'Inicia sesión con una cuenta personal de Google para desbloquear unas 1.000 solicitudes gratis al día antes de pagar nada.', ar: 'سجّل الدخول بحساب Google شخصي لفتح نحو 1000 طلب مجاني يومياً قبل أن تدفع أي شيء.' },
    { en: 'Use its built-in Google Search grounding for tasks that need up-to-date facts, not just code.', fr: 'Utilisez son ancrage à la recherche Google intégré pour les tâches qui nécessitent des faits à jour, pas seulement du code.', es: 'Usa su anclaje integrado a la búsqueda de Google para tareas que necesitan datos actualizados, no solo código.', ar: 'استخدم ربطه المدمج ببحث Google للمهام التي تتطلّب معلومات محدّثة لا مجرّد شيفرة.' },
  ],
  'openai-operator': [
    { en: 'Give Operator narrow, well-defined web tasks (one booking, one form) — it is unreliable on long multi-site journeys.', fr: 'Confiez à Operator des tâches web étroites et bien définies (une réservation, un formulaire) — il est peu fiable sur les longs parcours multi-sites.', es: 'Asigna a Operator tareas web concretas y bien definidas (una reserva, un formulario): no es fiable en recorridos largos entre varios sitios.', ar: 'كلّف Operator بمهام ويب ضيّقة ومحدّدة (حجز واحد، نموذج واحد) — فهو غير موثوق في الرحلات الطويلة عبر مواقع متعددة.' },
    { en: 'Stay nearby to confirm sensitive steps; never let it complete payments unattended.', fr: 'Restez à proximité pour confirmer les étapes sensibles ; ne le laissez jamais finaliser des paiements sans surveillance.', es: 'Mantente cerca para confirmar pasos sensibles; nunca dejes que complete pagos sin supervisión.', ar: 'ابقَ قريباً لتأكيد الخطوات الحسّاسة؛ ولا تدعه يُكمل عمليات الدفع دون إشراف.' },
  ],

  // ===== Top mainstream tools =====
  chatgpt: [
    { en: 'Set your role, tone and constraints once in Custom Instructions so you stop re-explaining context in every chat.', fr: 'Définissez votre rôle, votre ton et vos contraintes une fois dans les Instructions personnalisées pour ne plus réexpliquer le contexte à chaque conversation.', es: 'Define tu rol, tono y restricciones una vez en las Instrucciones personalizadas para no volver a explicar el contexto en cada chat.', ar: 'حدّد دورك ونبرتك وقيودك مرة واحدة في « التعليمات المخصّصة » حتى لا تعيد شرح السياق في كل محادثة.' },
    { en: 'For anything time-sensitive, switch on web/search mode — the base model’s knowledge has a cutoff date.', fr: 'Pour tout ce qui est sensible au temps, activez le mode web/recherche — les connaissances du modèle de base ont une date limite.', es: 'Para cualquier cosa sensible al tiempo, activa el modo web/búsqueda: el conocimiento del modelo base tiene una fecha de corte.', ar: 'لأي شيء مرتبط بالوقت، فعّل وضع الويب/البحث — فمعرفة النموذج الأساسي لها تاريخ توقّف.' },
  ],
  claude: [
    { en: 'Paste long documents directly — Claude’s large context handles entire reports without chunking them.', fr: 'Collez directement de longs documents — le grand contexte de Claude gère des rapports entiers sans les découper.', es: 'Pega documentos largos directamente: el amplio contexto de Claude maneja informes enteros sin trocearlos.', ar: 'الصق المستندات الطويلة مباشرة — يتعامل سياق Claude الكبير مع تقارير كاملة دون تقسيمها.' },
    { en: 'Ask it to "think step by step" on complex reasoning; it noticeably improves accuracy.', fr: 'Demandez-lui de « réfléchir étape par étape » sur un raisonnement complexe ; la précision s’améliore nettement.', es: 'Pídele que «piense paso a paso» en razonamientos complejos; mejora notablemente la precisión.', ar: 'اطلب منه « التفكير خطوة بخطوة » في الاستدلال المعقّد؛ فذلك يحسّن الدقة بوضوح.' },
  ],
  gemini: [
    { en: 'Gemini is strongest inside Google Workspace — use it in Docs and Gmail for context-aware help.', fr: 'Gemini est le plus performant dans Google Workspace — utilisez-le dans Docs et Gmail pour une aide contextuelle.', es: 'Gemini rinde mejor dentro de Google Workspace: úsalo en Docs y Gmail para ayuda contextual.', ar: 'يكون Gemini أقوى داخل Google Workspace — استخدمه في Docs وGmail للحصول على مساعدة مدركة للسياق.' },
    { en: 'Use its very large context to analyse long videos or massive documents in a single pass.', fr: 'Utilisez son très grand contexte pour analyser de longues vidéos ou d’énormes documents en une seule passe.', es: 'Usa su enorme contexto para analizar vídeos largos o documentos enormes de una sola pasada.', ar: 'استخدم سياقه الكبير جداً لتحليل مقاطع فيديو طويلة أو مستندات ضخمة دفعة واحدة.' },
  ],
  perplexity: [
    { en: 'Reach for Perplexity over a plain chatbot when you need cited, up-to-date sources you can click and verify.', fr: 'Préférez Perplexity à un chatbot classique quand vous avez besoin de sources récentes et citées, que vous pouvez cliquer et vérifier.', es: 'Recurre a Perplexity en vez de a un chatbot normal cuando necesites fuentes citadas y actualizadas que puedas verificar.', ar: 'استخدم Perplexity بدلاً من روبوت محادثة عادي عندما تحتاج مصادر محدّثة وموثّقة يمكنك النقر عليها والتحقق منها.' },
    { en: 'Switch the Focus mode to Academic for papers and Web for general queries to get sharper results.', fr: 'Basculez le mode Focus sur Académique pour les articles et Web pour les requêtes générales afin d’obtenir des résultats plus précis.', es: 'Cambia el modo Focus a Académico para artículos y Web para consultas generales para obtener resultados más precisos.', ar: 'بدّل وضع التركيز إلى « أكاديمي » للأبحاث و« ويب » للاستفسارات العامة للحصول على نتائج أدق.' },
  ],
  midjourney: [
    { en: 'Add --ar 16:9 and --style raw for cinematic, less over-stylised results.', fr: 'Ajoutez --ar 16:9 et --style raw pour des résultats cinématographiques et moins « stylisés ».', es: 'Añade --ar 16:9 y --style raw para resultados cinematográficos y menos sobreestilizados.', ar: 'أضِف ‎--ar 16:9‎ و‎--style raw‎ للحصول على نتائج سينمائية وأقل مبالغة في التنميق.' },
    { en: 'Use --cref (character reference) to keep the same character consistent across multiple images.', fr: 'Utilisez --cref (référence de personnage) pour garder le même personnage cohérent sur plusieurs images.', es: 'Usa --cref (referencia de personaje) para mantener el mismo personaje consistente en varias imágenes.', ar: 'استخدم ‎--cref‎ (مرجع الشخصية) للحفاظ على ثبات الشخصية نفسها عبر عدة صور.' },
  ],
  dalle3: [
    { en: 'DALL·E 3 follows long, detailed prompts well — describe composition, lighting and mood in full sentences.', fr: 'DALL·E 3 suit bien les prompts longs et détaillés — décrivez composition, éclairage et ambiance en phrases complètes.', es: 'DALL·E 3 sigue bien los prompts largos y detallados: describe composición, iluminación y ambiente en frases completas.', ar: 'يتّبع DALL·E 3 الأوامر الطويلة والمفصّلة جيداً — صِف التكوين والإضاءة والأجواء بجمل كاملة.' },
    { en: 'Generate it inside ChatGPT so you can refine the image conversationally, one tweak at a time.', fr: 'Générez-le dans ChatGPT pour affiner l’image par la conversation, un ajustement à la fois.', es: 'Génera dentro de ChatGPT para refinar la imagen conversando, un ajuste a la vez.', ar: 'أنشئها داخل ChatGPT لتحسين الصورة عبر المحادثة، تعديلاً تلو الآخر.' },
  ],
  cursor: [
    { en: 'Use @codebase in chat so Cursor answers with context from your whole project, not just the open file.', fr: 'Utilisez @codebase dans le chat pour que Cursor réponde avec le contexte de tout votre projet, pas seulement du fichier ouvert.', es: 'Usa @codebase en el chat para que Cursor responda con el contexto de todo tu proyecto, no solo del archivo abierto.', ar: 'استخدم @codebase في المحادثة ليجيب Cursor باستخدام سياق مشروعك بالكامل لا الملف المفتوح فقط.' },
    { en: 'Add a .cursorrules file to enforce your conventions on every AI edit automatically.', fr: 'Ajoutez un fichier .cursorrules pour imposer vos conventions à chaque modification IA automatiquement.', es: 'Añade un archivo .cursorrules para imponer tus convenciones en cada edición de IA automáticamente.', ar: 'أضِف ملف ‎.cursorrules‎ لفرض اصطلاحاتك على كل تعديل بالذكاء الاصطناعي تلقائياً.' },
  ],
  'github-copilot': [
    { en: 'Write a clear function name and docstring first — Copilot’s completions get dramatically better with stated intent.', fr: 'Écrivez d’abord un nom de fonction et une docstring clairs — les complétions de Copilot s’améliorent nettement avec une intention explicite.', es: 'Escribe primero un nombre de función y un docstring claros: las sugerencias de Copilot mejoran mucho con la intención declarada.', ar: 'اكتب أولاً اسم دالة و docstring واضحين — تتحسّن اقتراحات Copilot كثيراً عند توضيح النية.' },
    { en: 'Use Copilot Chat’s /tests and /fix slash commands instead of typing prompts from scratch.', fr: 'Utilisez les commandes /tests et /fix de Copilot Chat plutôt que de taper des prompts depuis zéro.', es: 'Usa los comandos /tests y /fix de Copilot Chat en vez de escribir prompts desde cero.', ar: 'استخدم أوامر ‎/tests‎ و‎/fix‎ في Copilot Chat بدلاً من كتابة الأوامر من الصفر.' },
  ],
  elevenlabs: [
    { en: 'Clone a voice from one to two minutes of clean, noise-free audio — quality drops fast with messy samples.', fr: 'Clonez une voix à partir d’une à deux minutes d’audio propre et sans bruit — la qualité chute vite avec des échantillons médiocres.', es: 'Clona una voz a partir de uno o dos minutos de audio limpio y sin ruido: la calidad cae rápido con muestras malas.', ar: 'استنسخ صوتاً من دقيقة إلى دقيقتين من صوت نظيف خالٍ من الضوضاء — تنخفض الجودة بسرعة مع العيّنات الرديئة.' },
    { en: 'Tune the stability and clarity sliders: lower stability adds emotion, higher keeps the voice consistent.', fr: 'Réglez les curseurs de stabilité et de clarté : une stabilité basse ajoute de l’émotion, une stabilité haute garde la voix constante.', es: 'Ajusta los controles de estabilidad y claridad: menor estabilidad añade emoción, mayor mantiene la voz consistente.', ar: 'اضبط شريطي الثبات والوضوح: الثبات المنخفض يضيف عاطفة، والمرتفع يحافظ على ثبات الصوت.' },
  ],
  suno: [
    { en: 'Put structure tags like [verse] and [chorus] in the lyrics and genre/mood in the style box for cleaner songs.', fr: 'Mettez des balises de structure comme [verse] et [chorus] dans les paroles, et le genre/l’ambiance dans le champ style, pour des morceaux plus nets.', es: 'Pon etiquetas de estructura como [verse] y [chorus] en la letra y género/ánimo en el campo de estilo para canciones más limpias.', ar: 'ضع وسوم البنية مثل [verse] و[chorus] في الكلمات والنوع/المزاج في خانة النمط للحصول على أغانٍ أنظف.' },
    { en: 'Generate several takes and stitch the best sections together — first outputs are rarely the best.', fr: 'Générez plusieurs versions et assemblez les meilleures sections — les premiers résultats sont rarement les meilleurs.', es: 'Genera varias tomas y une las mejores secciones: los primeros resultados rara vez son los mejores.', ar: 'أنشئ عدة محاولات وادمج أفضل المقاطع معاً — نادراً ما تكون المخرجات الأولى هي الأفضل.' },
  ],
};
